config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin, skip: [:registration, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :parks, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:destroy]
  end

  devise_for :users

  scope module: :public do
    root to: "homes#top"

    resources :parks, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]

    get "/homes/about", to: "homes#about", as: 'about'

    get "/search", to: "searches#search"
    
    post 'guest_login', to: 'users#guest_login'
  end
end

app/models/park.rb
class Park < ApplicationRecord
  has_one_attached :image

  belongs_to :user, optional: true
  has_many :posts, dependent: :restrict_with_error

  has_many :park_equipments, dependent: :destroy
  has_many :equipments, through: :park_equipments

  has_many :park_facilities, dependent: :destroy
  has_many :facilities, through: :park_facilities
  
  has_many :park_age_groups, dependent: :destroy
  has_many :age_groups, through: :park_age_groups

  validates :park_name, presence: true
  validates :introduction, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Park.where(park_name: content)
    elsif method == 'forward'
      Park.where('park_name LIKE ?', content + '%')
    elsif method == 'backward'
      Park.where('park_name LIKE ?', '%' + content)
    else 
      Park.where('park_name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/admin/parks_controller.rb
class Admin::ParksController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  def index
    @parks = Park.all
  end

  def show
    @posts = @park.posts
  end

  def edit
  end

  def update
    if @park.update(park_params)
    redirect_to admin_park_path(@park), notice: "編集しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @park.destroy
      redirect_to admin_parks_path, notice: '公園を削除しました。'
    else
      flash[:alert] = '投稿が存在するレコードは削除できません。'
      redirect_to admin_park_path(@park)
    end
  end

  private

  def park_params
    params.require(:park).permit(
      :park_name, :image, :introduction, :postal_code, :address,
      equipment_ids: [],
      facility_ids: [],
      age_group_ids: [])
  end

  def set_park
    @park = Park.find(params[:id])
  end  

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    @park.user_id = current_user.id
    if @park.save
    redirect_to parks_path(park_id: @park.id), notice: "公園を登録しました。"
    else
      reder :new, status: :unprocessable_entity
    end
  end 

  def index
    @parks = Park.all
  
  end

  def show
    @park = Park.find(params[:id])
    @post = Post.new
    @posts = @park.posts.order(created_at: :desc)
    @user = @park.user
  end

  def edit
  end

  def update
    @park.update(park_params)
     flash[:notice] = "編集しました"
    redirect_to park_path(@park.id)
  end

  def destroy
    @park.destroy
     flash[:notice] = "削除しました"
    redirect_to parks_path
  end

  private

  def park_params
    params.require(:park).permit(
      :park_name, :image, :introduction, :postal_code, :address,
      equipment_ids: [],
      facility_ids: [],
      age_group_ids: [])
  end

  def correct_user
    @park = current_user.parks.find_by(id: params[:id])
    redirect_to root_path unless @park

    #上と同じ結果になるコード
    #@park = Park.find_by(id: params[:id])
    #user = @park.user
    #if current_user != user
    #  redirect_to root_path
    #end
  end
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/parks/_new_post_form.html.erb
<h3>投稿フォーム</h3>

<%= render 'layouts/error_messages', post: post %>

<%= render "posts/form", post: post, park: park, submit: "投稿" %>

app/views/parks/_park_info.html.erb
<h3>公園詳細</h3>

<% if park.image.attached? %>
  <%= image_tag park.image, class: "img-fluid" %>
<% else %>
  <%= image_tag 'no_image_square', class: "img-fluid" %>
<% end %>

<table class="table">
  <tbody>
    <tr>
      <th>公園名</th>
      <td><%= park.park_name %></td>
    </tr>
    <tr>
      <th>説明</th>
      <td><%= park.introduction %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= park.postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= park.address %></td>
    </tr>
    <tr>
      <th>遊具</th>
      <td><%= park.equipments.pluck(:name).join("、") %></td>
    </tr>
    <tr>
      <th>設備</th>
      <td><%= park.facilities.pluck(:name).join("、") %></td>
    </tr>
    <tr>
      <th>年齢層</th>
      <td><%= park.age_groups.pluck(:name).join("、") %></td>
    </tr>
    <tr>
      <th>登録者</th>
      <td><%= park.user.name %></td>
    </tr>
    <tr>
      <th>登録日</th>
      <td><%= park.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
  </tbody>
</table>

<% if park.user == current_user %>
  <%= link_to "編集", edit_park_path(park) %> |
  <%= link_to "削除", park_path(park), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<% end %>

app/views/parks/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'parks/park_info', park: @park %>
    <%= render 'parks/new_post_form', post: @post, park: @park %>
  </div>

  <div class="col-md-8">
   <h1><%= @park.park_name %>  の投稿</h1>
   
   <ul class="list-unstyled">
    <% @posts.each do |post| %>
     <li class="d-flex align-items-start mb-4 border-bottom pb-3">
        <div class="flex-shrink-0" style="width: 150px;"> 
         <%= link_to post_path(post) do %>
           <%= image_tag post.get_image, class: "img-fluid rounded" %>
         <% end %>
        </div>
       
        <div class="flex-grow-1">
          <h5><%= post.title %></h5>
          <p class="mb-0 text-secondary"><%= post.body %></p>
          <p class="mb-1 text-muted" >投稿者 : <%= post.user.name %></p>
        </div>
      </li>
     <% end %>
    </ul>
  </div>
</div>