config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin, skip: [:registration, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :parks, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:destroy]
  end

  devise_for :users

  scope module: :public do
    root to: "homes#top"

    resources :parks, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]

    get "/homes/about", to: "homes#about", as: 'about'

    get "/search", to: "searches#search"
    
    post 'guest_login', to: 'users#guest_login'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :parks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  validates :name, presence: true
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else 
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def self.guest
    user = self.find_or_initialize_by(email: "guest@test.com")
    user.assign_attributes(
      password: SecureRandom.hex(6),
      name: "ゲスト"
    )
    user.save
    user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :destroy]


  def index
    @users = User.all
  end

  def show
    @posts = @user.posts.includes(:user).order(created_at: :desc)
    @parks = @user.parks if defined?(@user.parks)
  end

  def destroy
     @user.destroy 
     redirect_to admin_users_path, notice: 'ユーザーを削除しました。' 
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @park = @user.parks
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "編集しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "編集に失敗しました"
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<div class="card shadow-sm mb-4">
  <div class="card-body text-center">

    <%= image_tag @user.get_profile_image(100,100), class: "img-fluid rounded-circle mb-3", style: "object-fit:cover;" %>
    <h5 class="card-title"><%= @user.name %></h5>
    <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-outline-primary btn-sm mt-2" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
      <%= render 'list', user: @user %>
  </div>

  <div class="col-md-9">
    <h2 class="mb-4">Park</h2>
     
       <% @posts.each do |post| %>
         <div class="card mb-3 shadow-sm">
           <div class="row no-gutters align-items-center">
            <div class="col-md-4 text-cener p-2">
              <%= link_to post_path(post.id) do %>
                <%= image_tag post.get_image, size: "200x200", class: "img-fluid rounded", style: "object-fit:cover;" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">
                  <%= post.title %></h5>
                   <p class="card-text"><%= post.body %></p>
                   <p class="card-text">
                  <small class="text-muted">
                   <%= link_to park_path(post.park), class: "text-decoration-none" do %>
                    <%= post.park.park_name%>
                   <% end %>
             |      <%= post.created_at.strftime("%Y/%m/%d") %></small>
                   </p>
              </div>
            </div>
          </div>
        </div>
       <% end %>
  </div>
</div>