config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin, skip: [:registration, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :parks, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:destroy]
  end

  devise_for :users

  scope module: :public do
    root to: "homes#top"

    resources :parks, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]

    get "/homes/about", to: "homes#about", as: 'about'

    get "/search", to: "searches#search"
    
    post 'guest_login', to: 'users#guest_login'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :parks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  validates :name, presence: true
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else 
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def self.guest
    user = self.find_or_initialize_by(email: "guest@test.com")
    user.assign_attributes(
      password: SecureRandom.hex(6),
      name: "ゲスト"
    )
    user.save
    user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  before_action :set_user, only: [:show, :destroy]


  def index
    @users = User.all
  end

  def show
    @posts = @user.posts.includes(:user).order(created_at: :desc)
    @parks = @user.parks if defined?(@user.parks)
  end

  def destroy
     @user.destroy 
     redirect_to admin_users_path, notice: 'ユーザーを削除しました。' 
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @park = @user.parks
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "編集しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "編集に失敗しました"
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>ユーザー 一覧</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">名前</th>
        <th scope="col">Email</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "show", admin_user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>      

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h5><%= @user.name %>さんの会員詳細</h5>
        <%= button_to 'ユーザー削除', [:admin, @user], method: :delete, 
            data: { confirm: '本当にユーザーを削除しますか？' }, class: "btn btn-sm btn-danger" %>
    </div>
      <%= image_tag @user.get_profile_image(100,100), class: "img-fluid rounded-circle mb-3",
          style: "object-fit:cover;" %>     
        <table class="table">
          <tbody>
           <tr>
              <th>会員ID</th>
              <td><%= @user.id %></td>
            </tr>
            <tr>
            <tr>
              <th>名前</th>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th>email</th>
              <td><%= @user.email %></td>
            </tr>
            </tbody>
        </table>
   </div>
  <div class="col-md-7 border-left d-none d-md-block pl-md-4">
     <h5>投稿一覧</h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <% @posts.each do |post| %>
                <div class="row no-gutters align-items-start border-top">
                  <div class="col-md-5 mb-3 mb-md-0 pr-md-3">
                      <%= image_tag post.get_image, class: "img-fluid rounded", style: "width:100px;height:100px;object-fit:cover;" %>
                  </div>
                  <div class="col-md-7"> 
                  <%= post.user.name %>さん
                    <small class="text-muted ml-2"> <%= post.created_at.strftime('%Y/%m/%d') %></small>
                    <%=render 'public/posts/rating_show', post: post %>            
                    <h3 class="h5 mb-0"><%= post.title %></h3> 
                    <p class="text-secondary"><%= post.body %></p>
                    <%= button_to '投稿削除', [:admin, post], method: :delete, data: { confirm: 'この投稿を削除しますか？' },
                     form: { class: 'd-inline' }, class: 'btn btn-sm btn-outline-danger' %>
                  </div>
                </div>      
              <% end %>
            </li>
          </ul>
   </div>
</div>
  <div class="text-center mt-3">
    <%= link_to "Back", admin_users_path, class: "font-weight-bold d-inline-block mt-3" %>
  </div>