config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin, skip: [:registration, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:index, :show, :destroy]
    resources :parks, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:destroy]
  end

  devise_for :users

  scope module: :public do
    root to: "homes#top"

    resources :parks, only: [:new, :create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, :destroy]

    get "/homes/about", to: "homes#about", as: 'about'

    get "/search", to: "searches#search"
    
    post 'guest_login', to: 'users#guest_login'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]
end

app/models/age_group.rb
class AgeGroup < ApplicationRecord
  has_many :park_age_groups, dependent: :destroy
  has_many :parks, through: :park_age_groups
  validates :name, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord

  has_many :park_equipments, dependent: :destroy
  has_many :parks, through: :park_equipments

  validates :name, presence: true, uniqueness: true
end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :park_facilities, dependent: :destroy
  has_many :parks, through: :park_facilities

  validates :name, presence: true,uniqueness: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/park.rb
class Park < ApplicationRecord
  has_one_attached :image

  belongs_to :user, optional: true
  has_many :posts, dependent: :restrict_with_error

  has_many :park_equipments, dependent: :destroy
  has_many :equipments, through: :park_equipments

  has_many :park_facilities, dependent: :destroy
  has_many :facilities, through: :park_facilities
  
  has_many :park_age_groups, dependent: :destroy
  has_many :age_groups, through: :park_age_groups

  validates :park_name, presence: true
  validates :introduction, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Park.where(park_name: content)
    elsif method == 'forward'
      Park.where('park_name LIKE ?', content + '%')
    elsif method == 'backward'
      Park.where('park_name LIKE ?', '%' + content)
    else 
      Park.where('park_name LIKE ?', '%' + content + '%')
    end
  end
end

app/models/park_age_group.rb
class ParkAgeGroup < ApplicationRecord
  belongs_to :park
  belongs_to :age_group
end

app/models/park_equipment.rb
class ParkEquipment < ApplicationRecord
  belongs_to :park
  belongs_to :equipment
end

app/models/park_facility.rb
class ParkFacility < ApplicationRecord
  belongs_to :park
  belongs_to :facility
end

app/models/post.rb
class Post < ApplicationRecord

has_one_attached :image
belongs_to :user
belongs_to :park
has_many :post_comments, dependent: :destroy
has_many :favorites, dependent: :destroy

validates :title, presence: true
validates :body, presence: true

def get_image
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image
end

def favorited_by?(user)
   favorites.exists?(user_id: user.id)
end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
 
  belongs_to :user
  belongs_to :post

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :parks, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post

  validates :name, presence: true
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else 
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def self.guest
    user = self.find_or_initialize_by(email: "guest@test.com")
    user.assign_attributes(
      password: SecureRandom.hex(6),
      name: "ゲスト"
    )
    user.save
    user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-warning">
    <%= @post.errors.count %>件のエラーが発生しました
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<a class="navbar-brand" href="#">ParkNote</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>  
      <li class="nav-item">
        <%= link_to new_park_path, class: "nav-link", data: {turbolinks: "false"} do %>
          <i class="fa-solid fa-tree"></i> 公園登録
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to parks_path, data: { turbolinks: false }, class: "nav-link" do %>
          <i class="fa-solid fa-list"></i> 公園一覧
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to posts_path, class: "nav-link" do %>
          <i class="fa-solid fa-list"></i> 投稿一覧
      <% end %>
      </li>
      <li class="nav-item">
        <%= link_to user_path(current_user.id), class: "nav-link" do %>
          <i class="fa-solid fa-user"></i> マイページ
        <% end %>
      </li>
       <li class="nav-item">
         <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do%>
           <i class="fa-solid fa-right-from-bracket"></i> ログアウト
         <% end %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
         <i class="fa-solid fa-house"></i> ホーム
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to about_path, class: "nav-link" do %>
         <i class="fa-solid fa-link"></i> アバウト
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class: "nav-link" do %>
         <i class="fa-solid fa-user-plus"></i>  新規登録
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, class: "nav-link" do %>
         <i class="fa-solid fa-right-to-bracket"></i> ログイン
        <% end %>
      </li> 
    <% end %>
  </ul>
</div>

app/views/layouts/_park_error_messages.html.erb
<% if @park.errors.any? %>
  <div class="alert alert-warning">
    <%= @park.errors.count %>件のエラーが発生しました
    <ul>
      <% @park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - ParkNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/e71241d1d0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
       <div class="container">
         <a class="navbar-brand" href="#">ParkNote</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_users_path, class: "nav-link" do %>
                <i class="fa-solid fa-user"></i> ユーザー
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_parks_path, class: "nav-link" do %>
                  <i class="fa-solid fa-tree"></i> 公園
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
                  <i class="fa-solid fa-right-from-bracket"></i> ログアウト
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
     </nav>
    </header>
      <div class="container pt-5">
        <%= render "layouts/flash_messages" %>
         <%= yield %>
      </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parknote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/e71241d1d0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <%= render 'layouts/nav_bar' %>
        </div>
      </nav>
      
      <% unless params[:controller].match(/home|registration|session/).present? %>
        <nav class="navber-light bg-light">
          <div class="container">
            <div class= "d-flex justify-content-end mb-2">
              <%= render "public/searches/form" %>
            </div>
          </div>
        </nav>
      <% end %>
    </header>
    <div class="container pt-5">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>